/// <reference types="cypress" />
context('Navigation', () => {
    it('Should return true if the page title is BCalc', () => {
      cy.visit('http://localhost:8080/')
      cy.contains('Bcalc')
    })
    /// ----> Add tests
    it('CT001 - Should Add two positive integers with sum equal to zero (0+0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })    
    it('CT002 - Should Add one positive integer with 0 (1+0=1)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1)
    })    
    it('CT003 - Should Add two integers (max value suported) (1+999999999998=999999999999)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('999.999.999.999').should('to.have.length', 1)
    })
    it('CT004 - Should Add two integers (force an overflow error) (1+999999999999=Error)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('Error').should('to.have.length', 1)
    })
    it('CT005 - Should Add two positive integers (34+8=42)', () => {
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('42').should('to.have.length', 1)
    })
    it('CT006 - Should Add numbers in sequence (1+7+12+25+34+47+56+68+73+80+99=502)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('502').should('to.have.length', 1)
    })
    it('CT007 - Should Add two positive floats with sum equal to zero (0.0+0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })
    it('CT008 - Should Add one positive float with 0 (0.1+0.0=0.1)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,1').should('to.have.length', 1)        
    })
    it('CT009 - Should Add two floats (max precision suported) (0.000000001+0.999999998=0.999999999)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('10').should('to.have.length', 1) 
    })
    it('CT010 - Should Add two floats (Pass max precision) ((0.000000000001+0.999999999999=1)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1)
    })
    it('CT011 - Should Add two positive floats (0.34+0.8=0.42)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,42').should('to.have.length', 1)    
    })
    it('CT012 - Should Add float numbers in sequence (0.1+0.7+0.12+0.25+0.34+0.47+0.56+0.68+0.73+0.80+0.99=5,74)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btnAdd]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('5,74').should('to.have.length', 1)
    })
    /// ----> Subtraction tests
    it('CT013 - Should Subtract two positive integers with sum equal to zero (0-0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })    
    it('CT014 - Should Subtract one positive integer with 0 (1-0=1)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1)
    })    
    it('CT015 - Should Subtract two integers (max value suported) (1-99.999.999.999=-99.999.999.998)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-99.999.999.998').should('to.have.length', 1)
    })
    it('CT016 - Should Subtract two integers (force an overflow error) (1-999999999999=Error)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('Error').should('to.have.length', 1)
    })
    it('CT017 - Should Subtract two positive integers (8-34=-26)', () => {
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-26').should('to.have.length', 1)
    })
    it('CT018 - Should Subtract numbers in sequence (1-7-12-25-34-47-56-68-73-80-99=-500)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-500').should('to.have.length', 1)
    })
    it('CT019 - Should Subtract two positive floats with sum equal to zero (0.0-0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })
    it('CT020 - Should Subtract one positive float with 0 (0.1-0.0=-0.1)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,1').should('to.have.length', 1)        
    })
    it('CT021 - Should Subtract two floats (max precision suported) (0.000000001-0.999999999=-9.999999998)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-9,999999998').should('to.have.length', 1) 
    })
    it('CT022 - Should Subtract two floats (Pass max precision) ((0.0000000001-9.9999999999=-9.9999999998)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-9,999999998').should('to.have.length', 1)
    })
    it('CT023 - Should Subtract two positive floats (0.08-0.34=-0.26)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,26').should('to.have.length', 1)    
    })
    it('CT024 - Should Subtract float numbers in sequence (0.1-0.7-0.12-0.25-0.34-0.47-0.56-0.68-0.73-0.80-0.99=-5,54)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Sub]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-5,54').should('to.have.length', 1)
    })
    /// ----> Multiplication tests
    it('CT025 - Should Multiply zero by zero (0*0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })    
    it('CT026 - Should Multiply one positive integer with 0 (1*0=1)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1)
    })    
    it('CT027 - Should Multiply two integers (max value suported) (1*999.999.999.999=999.999.999.999)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('999.999.999.999').should('to.have.length', 1)
    })
    it('CT028 - Should Multiply two integers (force an overflow error) (2*999999999999=Error)', () => {
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('Error').should('to.have.length', 1)
    })
    it('CT029 - Should Subtract two positive integers (8*34=272)', () => {
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('272').should('to.have.length', 1)
    })
    it('CT030 - Should Subtract numbers in sequence (1*7*12*25*34*47*56=187.924.800)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('187.924.800').should('to.have.length', 1)
    })
    it('CT031 - Should Multiply two positive floats with sum equal to zero (0.0*0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })
    it('CT032 - Should Multiply one positive float with 0 (0.1*0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)        
    })
    it('CT033 - Should Multiply two floats (max precision suported) (9,999999999*0,1=1)', () => {
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1) 
    })
    it('CT034 - Should Multiply two floats (roud to max precision) ((9.9999999999*0.0000000001=0,000000001)', () => {
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,000000001').should('to.have.length', 1)
    })
    it('CT035 - Should Multiply two positive floats (0.34*0.08=0,0272)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,0272').should('to.have.length', 1)    
    })
    it('CT036 - Should Multiply float numbers in sequence (0.1*0.7*0.12*0.25*0.34*0.47*0.56=0,00018792)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Mul]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-btn6]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,00018792').should('to.have.length', 1)
    })
    /// ----> Division tests
    it('CT037 - Should Divide zero by 1 (0/1=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)    
    })    
    it('CT038 - Should Divide one by zero 0 (1/0= ∞)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('∞').should('to.have.length', 1)
    })    
    it('CT039 - Should Divide two integers (max value suported) (999.999.999.999/1=999.999.999.999)', () => {
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('999.999.999.999').should('to.have.length', 1)
    })
    it('CT040 - Should Divide two integers (max precision) (1/999999999999=Error)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)
    })
    it('CT041 - Should Divide two positive integers (34/8=4,25)', () => {
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('4,25').should('to.have.length', 1)
    })
    it('CT042 - Should Divide numbers in sequence (1/7/12/25/34/47=0,0000003)', () => {
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0,000000298').should('to.have.length', 1)
    })
    it('CT043 - Should Divide zero by zero (floats) (0.0/0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('Error').should('to.have.length', 1)    
    })
    it('CT044 - Should Divide one positive float by 0 (0.1/0.0=0)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)        
    })
    it('CT045 - Should Divide two floats (max precision) (9,999999999/0,000000001=99.999.999.999)', () => {
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('99.999.999.999').should('to.have.length', 1) 
    })
    it('CT046 - Should Divide two floats (round) (0.0000000001/9.9999999999=1)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('1').should('to.have.length', 1)
    })
    it('CT047 - Should Divide two positive floats (0.34/0.08=4,25)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-btn8]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('4,25').should('to.have.length', 1)    
    })
    it('CT048 - Should Divide float numbers in sequence (0.1/0.7/0.12/0.25/0.34/0.47=29,7991537)', () => {
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn1]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn5]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn3]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-Div]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-decimal]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn7]').click()
        cy.get('[data-cy=bc-equal]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('29,7991537').should('to.have.length', 1)
    })
    /// ----> Special cases
    it('CT049 - Should Clean de visor when press C', () => {
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-btn9]').click()
        cy.get('[data-cy=bc-Clr]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('0').should('to.have.length', 1)
    })
    it('CT050 - Should Divide by 100 when press %', () => {
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-btn0]').click()
        cy.get('[data-cy=bc-Per]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('4,2').should('to.have.length', 1)
    })
    it('CT051 - Should invert de signal when press (+/-)', () => {
        cy.get('[data-cy=bc-Clr]').click()
        cy.get('[data-cy=bc-btn4]').click()
        cy.get('[data-cy=bc-btn2]').click()
        cy.get('[data-cy=bc-Sig]').click()
        cy.get('[data-cy=bc-display]').should('to.have.length', 1)
        cy.contains('-42').should('to.have.length', 1)
    })

})